### PR TITLE
vila_live: restore compatible Transformers dependencies

### PR DESCRIPTION
**Pull request by jcfr**
## Description

Restore the Transformers 4 dependency line used by the pinned [VILA revision](https://github.com/Efficient-Large-Model/VILA/blob/ec7fb2c264920bf004fd9fa37f1ec36ea0942db5/pyproject.toml), which declares Transformers 4.37.2, and [llm-awq revision](https://github.com/mit-han-lab/llm-awq/blob/41d7e704932b7eaf8b3dcfb21e1fe49fd296d894/pyproject.toml), which declares Transformers 4.36.2. HoloHub intentionally overrides those dependency declarations with Transformers 4.48 and carries an existing [llm-awq compatibility patch](https://github.com/nvidia-holoscan/holohub/blob/main/applications/vila_live/llm-awq.patch) for that version.

The grouped dependency update in [cfb37bbb3](https://github.com/nvidia-holoscan/holohub/commit/cfb37bbb32008ba5a89c46e0cfbf75f9a875d535) moved vila_live from Transformers 4.48 to 5.14 and Hugging Face Hub 0.36 to 1.24 while leaving the pinned VILA and llm-awq sources unchanged.

This change restores Transformers 4.48 and Hugging Face Hub 0.36.2 for both CUDA versions. It leaves the CUDA 13-specific Torch and FlashAttention selection introduced by #1611 unchanged because those binary dependencies, unlike Transformers, are CUDA-sensitive.

The TinyChat test now waits for the model worker to register, extracts a real frame from `meeting.mp4`, sends the same request shape used by `vlm.py` directly to the worker, and requires an error-free, non-empty generated response. Process cleanup is registered immediately after controller startup so partial setup failures cannot leave the test ports occupied.

## Failure addressed

With Transformers 5.14, the TinyChat worker repeatedly encountered removed or changed Transformers APIs during import and model initialization and exited before registration. These included relocated initialization helpers and changed RoPE and model-initialization interfaces. This was a Python dependency API mismatch rather than a CUDA 13 requirement.

Restoring the dependency versions used by the pinned VILA integration avoids maintaining a downstream Transformers 5 port while retaining CUDA 13 support through the existing Torch and FlashAttention paths.

## Tests

- `uvx pre-commit run --all-files`
- Clean CUDA 13 x86_64 application image build
- Focused `vila_live_vlm_test` and `vila_live_tinychat_test` using the built image
- Complete `vila_live` application using the replayer source and browser-equivalent WebSocket interaction

## Validation

Internal CUDA 13 validation on an x86_64 RTX A6000 completed successfully. The clean application image built with PyTorch 2.12.0+cu130, Transformers 4.48, Hugging Face Hub 0.36.2, and the existing CUDA 13 FlashAttention wheel.

A focused rerun using the exact final test implementation passed both VILA tests in 35.21 seconds. The TinyChat worker loaded the AWQ checkpoint, registered with the controller, accepted the application-compatible image-generation request, and returned: `Three people are sitting around a table in a meeting.`

Internal Jenkins HoloHub application nightly run 794 completed successfully for head 5561aee1d using the CUDA 13 `app_grp_6` dGPU flow. `vila_live_vlm_test` passed in 7.04 seconds and `vila_live_tinychat_test` passed in 40.84 seconds; 2/2 tests passed.

Full-application validation on the same head also passed on an internal x86_64 RTX A6000 system using `./holohub run vila_live --run-args="--source replayer"`. The controller and AWQ worker started and registered, the Holoscan graph processed replayed frames, the web application returned HTTP 200, and a browser-equivalent WebSocket client received a live frame and submitted `How many people are visible? Reply with only the number.` The application returned the non-empty response `4`, and cleanup left no application processes, listeners, container, or GPU workload running.

### CODE REVIEW

File: applications/vila_live/Dockerfile [hunk 1]
```diff
@@ -74,8 +74,9 @@ RUN if [ "${CUDA_MAJOR}" = "13" ] && [ "$(uname -m)" = "x86_64" ]; then \
 # ----------------------------------------------------------------------------
 # Clone and install AWQ based on the GPU's compute capacity
 # ----------------------------------------------------------------------------
-# Copy over patch file to patch llm-awq so that it works with transformers 4.48
+# Adapt pinned llm-awq and VILA revisions to the Transformers 5 APIs installed below.
```
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/Dockerfile]: Addressed in [f0fcad196](https://github.com/nvidia-holoscan/holohub/commit/f0fcad196b8d822a8a06b69ceba739518c07de89). Both nearby comments are now version-agnostic: the heading describes compatibility patches for the pinned revisions, and the llm-awq application comment describes fixes required by that pinned revision. The full pre-commit suite passes.

**Comment by tbirdso** [comment]
> Runtime validation still required:

@jcfr I'm concerned that the agent-driven tests in the PR description are sufficient. Can you please validate runtime correctness?

**Comment by jcfr** [comment]
Agreed; the previous process-startup check was not sufficient. I added a separate commit that makes `vila_live_tinychat_test` wait for the worker to register, extract a real frame from the test video, request image-to-text generation through the controller, and require an error-free, non-empty response.

Internal CUDA 13 validation in Jenkins HoloHub application nightly runs 786 and 788 identified additional Transformers 5 incompatibilities before worker registration, so runtime correctness is not yet established.

File: applications/vila_live/tests/test_tinychat.py [hunk 2]
```diff
@@ -75,54 +67,109 @@ def setUpClass(cls):
...
+        )
+        request_data = {
+            "model": self.model_name,
+            "prompt": prompt,
+            "temperature": 0.3,
+            "max_new_tokens": 8,
+            "images": [self._load_test_frame()],
+        }
+        response = requests.post(
+            "http://localhost:10000/worker_generate_stream",
```
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/tests/test_tinychat.py]: This finding does not apply to the pinned [mit-han-lab/llm-awq@41d7e7049](https://github.com/mit-han-lab/llm-awq/commit/41d7e704932b7eaf8b3dcfb21e1fe49fd296d894) revision. Its controller exposes [`POST /worker_generate_stream`](https://github.com/mit-han-lab/llm-awq/blob/41d7e704932b7eaf8b3dcfb21e1fe49fd296d894/tinychat/serve/controller.py#L299-L303), resolves the registered worker, and forwards the stream request. Using the controller intentionally validates registration and routing in addition to inference; the direct port 40000 endpoint remains the application's alternative path.

File: applications/vila_live/Dockerfile [hunk 3]
```diff
@@ -74,16 +74,17 @@ RUN if [ "${CUDA_MAJOR}" = "13" ] && [ "$(uname -m)" = "x86_64" ]; then \
 # ----------------------------------------------------------------------------
 # Clone and install AWQ based on the GPU's compute capacity
 # ----------------------------------------------------------------------------
-# Copy over patch file to patch llm-awq so that it works with transformers 4.48
+# Copy compatibility patches for the pinned llm-awq and VILA revisions.
 COPY applications/vila_live/llm-awq.patch /tmp/
+COPY applications/vila_live/vila-transformers5.patch /tmp/
```
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/Dockerfile]: The current branch commits [f1477a3fe](https://github.com/nvidia-holoscan/holohub/commit/f1477a3fe65d072c931def07f1fe9c532ed87350) and [7863093e9](https://github.com/nvidia-holoscan/holohub/commit/7863093e9456cec7d60b23784c6b9f8dafbb6eb6) both contain the required `Signed-off-by: Jean-Christophe Fillion-Robin <jcfr@nvidia.com>` trailer. The commit referenced by the stale finding is not a current branch commit, so this finding does not apply.

**Comment by jcfr** [comment]
Internal CUDA 13 validation in Jenkins HoloHub application nightly run 786 exposed compatibility failures that the former startup-only test did not detect. `vila_live_vlm_test` passed, but the TinyChat worker exited before registration at intermediate commit [1119f51ec](https://github.com/nvidia-holoscan/holohub/commit/1119f51ecc682de3866bfb9f11ab95864c272597):

```text
File "/workspace/VILA/llava/model/multimodal_encoder/image_processor.py",
line 39, in <module>
    from transformers.utils import (
ImportError: cannot import name 'is_tf_available' from 'transformers.utils'
```

The TensorFlow block in this pinned image processor is commented out, leaving `is_tf_available` unused. Commit [7863093e9](https://github.com/nvidia-holoscan/holohub/commit/7863093e9456cec7d60b23784c6b9f8dafbb6eb6) removes that obsolete import as part of the Transformers 5 compatibility patch.

Jenkins HoloHub application nightly run 788 validated that corrected commit. It progressed past the first import and exposed another removed Transformers 5 helper:

```text
File "/workspace/VILA/llava/model/language_model/modeling_mixtral_long_context.py",
line 53, in <module>
    from transformers.utils.import_utils import is_torch_fx_available
ImportError: cannot import name 'is_torch_fx_available' from
'transformers.utils.import_utils'
```

Transformers 4.48 used this helper only to require PyTorch 1.10 or newer before wrapping `_prepare_4d_causal_attention_mask` as an FX leaf. Transformers 5.14 requires PyTorch 2.4 or newer, and the CUDA 13 image pins PyTorch 2.12. Follow-up commit [74a5f7f9f](https://github.com/nvidia-holoscan/holohub/commit/74a5f7f9f107e3b2fa3fd107acefb7c4b5fa797a) removes the obsolete version helpers and calls `torch.fx.wrap` directly, preserving the behavior selected for every supported version.

Run 788 identified a real blocker and is not acceptance evidence. A focused CUDA 13 rerun of [74a5f7f9f](https://github.com/nvidia-holoscan/holohub/commit/74a5f7f9f107e3b2fa3fd107acefb7c4b5fa797a) must demonstrate worker registration and successful image-to-text generation before the PR is ready to merge.

**Comment by jcfr** [comment]
The fresh focused validation is
[HoloHub application nightly #788](https://prod.blsm.nvidia.com/clara-holoscan-sdk/blue/organizations/jenkins/holohub-app-nightly/detail/holohub-app-nightly/788/pipeline),
requested for corrected branch tip `7863093e9`. I will confirm the checked-out
SHA and post the runtime result after the run reaches the VILA test stage.

**Comment by wyli** [comment]
Targeted CUDA 13 validation at exact public commit `7863093e9456cec7d60b23784c6b9f8dafbb6eb6`: **FAIL, reproducing the remaining Transformers 5 incompatibility**.

- x86_64 NVIDIA A30
- `vila_live_vlm_test`: passed
- `vila_live_tinychat_test`: failed
- Overall: 1/2 tests passed

The worker exited before registration/generation through this import chain:

```text
/workspace/VILA/llava/model/language_model/modeling_mixtral_long_context.py:53
from transformers.utils.import_utils import is_torch_fx_available
ImportError: cannot import name 'is_torch_fx_available'
```

This confirmed that the intermediate patch advanced past the earlier `no_init_weights` and `is_tf_available` failures, but was not yet fully compatible with the installed Transformers 5 API. The targeted application images and workspace were cleaned afterward. This finding applies to that intermediate public commit and is superseded by the PR's later dependency-restoration changes.

**Comment by jcfr** [comment]
I replaced the incomplete Transformers 5 port with the narrower dependency fix validated at current head [1deba4c10](https://github.com/nvidia-holoscan/holohub/commit/1deba4c10fb8d2e1808d5e67c95523e297a9b189): restore Transformers 4.48 and Hugging Face Hub 0.36.2 while retaining the existing CUDA 13 PyTorch and FlashAttention path.

Internal CUDA 13 validation on x86_64 completed a clean application-image build and then ran the focused TinyChat runtime test. The AWQ model loaded, the worker registered, and the test sent a real frame using the same worker endpoint and request fields as `vlm.py`. The test passed in 34.07 seconds and returned: `Three people are sitting around a table, working on a laptop and talking.`

I also addressed the cleanup review feedback by registering process cleanup immediately after controller startup, so a later setup failure cannot leave the test ports occupied. The full `uvx pre-commit run --all-files` suite passes.

File: applications/vila_live/tests/test_tinychat.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/tests/test_tinychat.py]: Addressed at [1deba4c10](https://github.com/nvidia-holoscan/holohub/commit/1deba4c10fb8d2e1808d5e67c95523e297a9b189). The test now posts directly to the model worker on port 40000 and uses the same `max_tokens`, `stop`, `n_keep`, and `stream` fields as `vlm.py`. Focused CUDA 13 runtime validation loaded and registered the worker and returned non-empty generated text through this path.

File: applications/vila_live/tests/test_tinychat.py [hunk 4]
```diff
@@ -75,54 +69,131 @@ def setUpClass(cls):
...
-                TypeError,
-                ValueError,
-            ) as e:
-                print(f"Error killing controller process: {e}")
+                os.killpg(os.getpgid(process.pid), signal.SIGTERM)
+                process.wait(timeout=10)
+            except subprocess.TimeoutExpired:
+                os.killpg(os.getpgid(process.pid), signal.SIGKILL)
+                process.wait(timeout=10)
+            except ProcessLookupError:
```
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/tests/test_tinychat.py:199]: Addressed at [1deba4c10](https://github.com/nvidia-holoscan/holohub/commit/1deba4c10fb8d2e1808d5e67c95523e297a9b189). The handler now explains that the process may exit between `poll()` and signaling and therefore needs no further cleanup. The relevant pre-commit hooks pass.

**Comment by jcfr** [comment]
I reworked this PR after runtime validation showed that continuing the Transformers 5 adaptation would require maintaining a broader downstream port across both pinned VILA and llm-awq.

The PR now restores the Transformers 4.48 and Hugging Face Hub 0.36.2 versions expected by those pinned sources while leaving the CUDA 13-specific PyTorch and FlashAttention installation unchanged. It retains the strengthened TinyChat test as a separate commit.

Focused CUDA 13 validation on an x86_64 RTX A6000 passed both VILA tests. The exact final TinyChat test loaded the AWQ checkpoint, registered the worker, performed image-to-text generation, returned `Three people are sitting around a table in a meeting.`, and shut down cleanly. Full pre-commit also passes after rebasing onto current `main`.

File: applications/vila_live/tests/test_tinychat.py [hunk 5]
```diff
@@ -75,54 +70,130 @@ def setUpClass(cls):
...
+                "-i",
+                video_path,
+                "-frames:v",
+                "1",
+                "-f",
+                "image2pipe",
+                "-vcodec",
+                "mjpeg",
+                "pipe:1",
+            ]
```
[the remark this answers is not in the document]
Comment (jcfr) [reply applications/vila_live/tests/test_tinychat.py:145]: Fixed in 5561aee1d. The test now resolves `ffmpeg` with `shutil.which()` and raises a clear error when it is unavailable, while retaining the fixed list-form, non-shell invocation. The full `uvx pre-commit run --all-files` suite passes. A narrow S603 suppression was not needed by the repository Ruff configuration and was removed as unused by its autofix.

**Comment by tbirdso** [comment]
@jcfr coverage looks better, but would it be possible to validation with one full end-to-end application run as well as the test coverage you've added here?

**Comment by jcfr** [comment]
Yes. The current validation exercises model loading and image-to-text generation through the TinyChat worker, but it does not launch the complete `vila_live` application.

I will run the exact PR head through the documented replayer path (`./holohub run vila_live --run-args="--source replayer"`) and verify that the controller and worker start, the Holoscan graph consumes the recorded video, the web application becomes available, and a prompt submitted through the application produces a non-empty response from the model. I will report the result here before considering the PR ready to merge.

**Comment by jcfr** [comment]
@tbirdso Full-application runtime validation is now complete on the exact PR head 5561aee1d.

On an internal x86_64 RTX A6000 system, `./holohub run vila_live --run-args="--source replayer"` started the controller and AWQ worker, registered the model, processed replayed frames through the Holoscan graph, and served the web application successfully. A browser-equivalent WebSocket client received a live frame, submitted `How many people are visible? Reply with only the number.`, and received the non-empty model response `4` through the application's actual UI protocol.

The runtime container and client shut down cleanly with no residual application processes, listeners, container, or GPU workload. This validates the complete application path in addition to the focused TinyChat and Jenkins tests already reported above.

**Comment by wyli** [comment]
Revalidated the current head `5561aee1d2837a7b306913e68be3b8633f776d69` with focused CUDA 13 `vila_live` application tests.

On an x86_64 NVIDIA A30 (Ampere/SM80):

- The final image contained `transformers 4.48.3` and `huggingface-hub 0.36.2`.
- `vila_live_vlm_test`: passed.
- `vila_live_tinychat_test`: passed, including worker registration and a non-empty image-to-text generation response.
- Overall: **2/2 tests passed**.

An additional run of the same head on an SM100/Blackwell-class GPU reached worker registration, but TinyChat generation failed with `CUDA error: an illegal memory access was encountered`; the other VILA test passed (1/2 overall). This isolates a GPU-architecture-specific AWQ runtime issue rather than a failure of the restored Transformers dependencies. If SM100 is in support scope, it should be tracked separately; otherwise this application/test should be constrained to validated GPU architectures for now.

Generated application images and workspaces were cleaned after both runs.

**Review by wyli — APPROVED** [review]

**Review by tbirdso — APPROVED** [review]
