### PR TITLE
App: Fix Endoscopy Tool Tracking compatibility on IGX OS host environment

### PR DESCRIPTION
**Pull request by tbirdso**
## Overview

Followup to 4ae73c0ef67e648f10db8fd9e063c36313c1070d to restore IGX Orin dGPU bare metal build and runtime compatibility to the Endoscopy Tool Tracking demo app.

## Background

deebc27f1244032797d422016d81e14874f6cbb1 added SlangShaderOp support to the Endoscopy Tool Tracking application. Tests and inspection reveal that the SlangShaderOp is not currently compatible with the IGX OS 1.x build and runtime environment.

- IGX OS 1.x: CUDA Driver R535, CUDA Toolkit 12.6, GCC 11.4, GLIBC 2.35
- SlangShaderOp: CUDA Toolkit >= 12.8 (previous) or >= 12.0 (updated)
  - libslang.so: GCC >= 13

## Changes

Updates Endoscopy Tool Tracking and SlangShaderOp as follows:
- Makes SlangShaderOp an optional build and runtime dependency of Endoscopy Tool Tracking. A similar approach is used for other optional operators such as the VTK renderer.
- Fixes leftover CUDA Runtime symbol `cudaLibrary_t` in SlangShaderOp to update compatibility from CTK >= 12.8 to CTK >= 12.0. Fixes compilation error with CTK 12.6 (tested)

Fixes observed error when building on IGX OS 1.1.2:
```
$ ./holohub build --local endoscopy_tool_tracking
...
[7/37] Building CXX object operators/slang_shader/cpp/CMakeFiles/slang_shader.dir/slang_shader_compiler.cpp.o
FAILED: operators/slang_shader/cpp/CMakeFiles/slang_shader.dir/slang_shader_compiler.cpp.o 
/usr/bin/c++ -DEIGEN_MPL2_ONLY -DFMT_HEADER_ONLY=1 -DHOLOSCAN_MAJOR_VERSION=3 -DHOLOSCAN_MINOR_VERSION=5 -DRMM_LOG_ACTIVE_LEVEL=RAPIDS_LOGGER_LEVEL_INFO -DSLANG_DYNAMIC -DUCXX_ENABLE_RMM -DYAML_CPP_STATIC_DEFINE -Dslang_shader_EXPORTS -I/home/tbirdsong/repos/holohub/build/endoscopy_tool_tracking/operators/slang_shader/cpp -I/home/tbirdsong/repos/holohub/build/endoscopy_tool_tracking/_deps/nlohmann_json-src/include -isystem /home/tbirdsong/repos/holohub/build/endoscopy_tool_tracking/_deps/slang-src/include -isystem /opt/nvidia/holoscan/include -isystem /opt/nvidia/holoscan/include/3rdparty -isystem /opt/nvidia/holoscan/include/gxf -isystem /usr/local/cuda/targets/sbsa-linux/include -isystem /opt/nvidia/holoscan/include/3rdparty/ucx -isystem /opt/nvidia/holoscan/include/3rdparty/ucxx -O3 -DNDEBUG -fPIC -MD -MT operators/slang_shader/cpp/CMakeFiles/slang_shader.dir/slang_shader_compiler.cpp.o -MF operators/slang_shader/cpp/CMakeFiles/slang_shader.dir/slang_shader_compiler.cpp.o.d -o operators/slang_shader/cpp/CMakeFiles/slang_shader.dir/slang_shader_compiler.cpp.o -c /home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp
/home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp: In lambda function:
/home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp:76:7: error: ‘cudaLibrary_t’ was not declared in this scope; did you mean ‘cudaArray_t’?
   76 |       cudaLibrary_t library;
      |       ^~~~~~~~~~~~~
      |       cudaArray_t
In file included from /home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.hpp:28,
                 from /home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp:18:
/home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp:78:12: error: ‘library’ was not declared in this scope; did you mean ‘CUlibrary’?
   78 |           &library, ptx_code->getBufferPointer(), nullptr, nullptr, 0, nullptr, nullptr, 0));
      |            ^~~~~~~
/home/tbirdsong/repos/holohub/operators/slang_shader/cpp/cuda_utils.hpp:73:35: note: in definition of macro ‘CUDA_CALL’
   73 |     CUresult _holoscan_cuda_err = stmt;                                                   \
      |                                   ^~~~
/home/tbirdsong/repos/holohub/operators/slang_shader/cpp/slang_shader_compiler.cpp:79:14: error: ‘library’ was not declared in this scope; did you mean ‘CUlibrary’?
   79 |       return library;
      |              ^~~~~~~
      |              CUlibrary
```

- Adds compiler check to enforce GCC >= 13 when linking against libslang.so. Fixes observed linking error:
```
    /usr/bin/ld: .../holohub-internal/build/endoscopy_tool_tracking/_deps/slang-src/lib/libslang.so: undefined reference t
o `fmodf@GLIBC_2.38'
```

## Testing

Verified Endoscopy Tool Tracking tests pass in the IGX dGPU OS 1.1.2 host environment with Holoscan SDK 3.5.0 Debian package and Python wheel installed. SlangShaderOp test coverage is disabled by default.
```
$ xvfb-run -a ctest -C Release
Test project /home/tbirdsong/repos/holohub/build/endoscopy_tool_tracking
    Start 1: endoscopy_tool_tracking_cpp_test
1/4 Test #1: endoscopy_tool_tracking_cpp_test .............   Passed    1.36 sec
    Start 2: endoscopy_tool_tracking_cpp_render_test
2/4 Test #2: endoscopy_tool_tracking_cpp_render_test ......   Passed    2.08 sec
    Start 3: endoscopy_tool_tracking_python_test
3/4 Test #3: endoscopy_tool_tracking_python_test ..........   Passed    1.67 sec
    Start 4: endoscopy_tool_tracking_python_render_test
4/4 Test #4: endoscopy_tool_tracking_python_render_test ...   Passed    2.09 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   7.21 sec
```

### CODE REVIEW

File: operators/slang_shader/cpp/slang_shader_compiler.cpp [hunk 1]
```diff
@@ -72,12 +72,11 @@ SlangShaderCompiler::SlangShaderCompiler(const Slang::ComPtr<slang::ISession>& s
...
-      cudaLibrary_t library;
-      CUDA_CALL(cuLibraryLoadData(
-          &library, ptx_code->getBufferPointer(), nullptr, nullptr, 0, nullptr, nullptr, 0));
-      return library;
-    }());
+    CUlibrary library;
+    CUDA_CALL(cuLibraryLoadData(
+        &library, ptx_code->getBufferPointer(), nullptr, nullptr, 0, nullptr, nullptr, 0));
+
+    cuda_libraries_.emplace_back(library);
```
Comment (ghost) [inline operators/slang_shader/cpp/slang_shader_compiler.cpp]: Any reason to change this?

File: operators/slang_shader/cpp/slang_shader_compiler.cpp [hunk 2]
```diff
@@ -17,7 +17,7 @@
 
 #include "slang_shader_compiler.hpp"
 
-#include <driver_types.h>
+#include <cuda.h>
```
Comment (ghost) [inline operators/slang_shader/cpp/slang_shader_compiler.cpp:20]: Why is this change required?

**Review by AndreasHeumann — COMMENTED** [review]
>Fixes leftover CUDA Runtime symbols in SlangShaderOp to update compatibility from >CTK >= 12.8 to CTK >= 12.0. Fixes compilation error with CTK 12.6 (tested)

I don't see that there were any 12.8 CUDA runtime symbols before. The change from `cudaStream_t` to `cuStream` is fine but this is just a typedef not a link time symbol.

File: operators/slang_shader/cpp/slang_shader_compiler.cpp (hunk 1 above)
Comment (tbirdso) [reply operators/slang_shader/cpp/slang_shader_compiler.cpp]: You're right, I got carried away. The only fix strictly required to compile with CTK 12.6 seems to be the cudaLibrary_t -> CUlibrary change.

I've reverted other changes in this file and also updated the PR description with the original error message from IGX dGPU.

File: operators/slang_shader/cpp/slang_shader_compiler.cpp (hunk 2 above)
Comment (tbirdso) [reply operators/slang_shader/cpp/slang_shader_compiler.cpp:20]: driver_types.h defines cudaStream_t, I've reverted to add both back
